### ISSUE TITLE
This weird thing when I sign and close a book to address it, this is what I got...

### ISSUE THREAD

**Issue by MrKiller01** [ShadowJonathan/va_postal#2]
Hi, congrats on reviving this plugin, I do hope you can keep it alive as so many people would say....
However, I had this weird thing, I had a book and quill in my hand, I tried left and right hand, and wanted to give it an address... but it kept telling me that I need to have a signed book in my hand.... I have! Several times!!

So, I tried to find something on this error but I could not find it, there is also no error on the console that enlightens the situation for you. I hope I can help you solve this problem because this plugin is really worth using.....

Thanks

**Comment by ShadowJonathan** [comment]
could you please send me the commands that worked and didn't work for you? or didn't any of them work?

**Comment by GuiltyWatts** [comment]
Hello,

Just chiming in because I'm having the same issue. Here's a link to the imgur that has the screenshots on the problem. For the record, the command that I'm using is:

/addr <po location> <mailbox> <player>

It tells me I need to hold a signed book in my hand, but I already am.

Additionally, the following command strings dont work:

/setowner
/pk

When I use any of these, I get a message telling me to press "/" to confirm, but pressing / does nothing.

**Comment by ShadowJonathan** [comment]
> When I use any of these, I get a message telling me to press "/" to confirm, but pressing / does nothing.

You have to send the command or word "/" into chat, to confirm your selection/action

**Comment by GuiltyWatts** [comment]
Sorry, should have been more specific. I type '/' into chat. It does nothing

![image](https://user-images.githubusercontent.com/34111246/33406002-cd6e0310-d538-11e7-9b0a-f0d10a2616a6.png)

**Comment by ShadowJonathan** [comment]
*sigh*

Type it and **send it**

**Comment by GuiltyWatts** [comment]
You mean type '/' into the chat, and press enter. Yes, I know that. I'm doing that. Nothing happens. It doesn't even register that its happening. When creating a post office or setting a route, it behaves correctly. Its only when sending a package or setting an address that this comes up.

**Comment by ShadowJonathan** [comment]
you mean nothing happens at all?

I'll look into that, thank you, it might be a bug I unintentionally created.

**Comment by ShadowJonathan** [comment]
also, try /owneraddr and /ownerlocal

**Comment by GuiltyWatts** [comment]
![image](https://user-images.githubusercontent.com/34111246/33406700-255e4c80-d53c-11e7-85f5-20a59d83f505.png)

Tried it, it didnt work, but the error is different. It tells me it needs more letters? Did I get it wrong?

**Comment by ShadowJonathan** [comment]
I'm thinking this is essentials messing around with display names, thanks for reporting.

and I'll look into why /setowner does nothing.

**Comment by GuiltyWatts** [comment]
I appreciate your effort! Let me know if you need anything else on my end.

**Comment by ShadowJonathan** [comment]
no problem, could you maybe please screenshot the output of `/pl`? I want to see which plugins might take part in any of the problems

**Comment by GuiltyWatts** [comment]
![image](https://user-images.githubusercontent.com/34111246/33407130-d340db5a-d53d-11e7-8ec0-9762726606d8.png)

**Comment by ShadowJonathan** [comment]
thank you, I'll look into this
